export const SITE_METADATA = {
  name: 'الرحمة المهداه للتوظيف',
  shortName: 'الرحمة المهداه',
  subtitle: 'مركز التحكم التنفيذي',
  logoPath: '/logo-mark.png',
  adminLoginUrl: 'https://rahma-al-muhdah-admin.web.app/#/login',
  adminDashboardUrl: 'https://rahma-al-muhdah-admin.web.app/#/dashboard',
  primary: '#2563eb',
  primaryDark: '#1e40af',
  gold: '#f59e0b',
  cream: '#fdfbf7',
} as const;

export const PERMISSION_CATALOG = [
  { key: 'dashboard:view', label: 'عرض لوحة المتابعة' },
  { key: 'jobs:view', label: 'عرض الوظائف' },
  { key: 'jobs:create', label: 'إنشاء وظيفة' },
  { key: 'jobs:edit', label: 'تعديل الوظائف' },
  { key: 'jobs:publish', label: 'نشر الوظائف' },
  { key: 'jobs:archive', label: 'أرشفة الوظائف' },
  { key: 'applications:view', label: 'عرض الطلبات' },
  { key: 'applications:update', label: 'تحديث حالة الطلب' },
  { key: 'applications:assign', label: 'إسناد الطلبات' },
  { key: 'applications:export', label: 'تصدير الطلبات' },
  { key: 'companies:view', label: 'عرض الشركات' },
  { key: 'companies:review', label: 'مراجعة الشركات' },
  { key: 'companies:approve', label: 'اعتماد الشركات' },
  { key: 'companies:password_reset', label: 'إعادة تعيين كلمة سر الشركة' },
  { key: 'companies:archive', label: 'أرشفة الشركات' },
  { key: 'users:view', label: 'عرض المستخدمين' },
  { key: 'users:edit', label: 'تعديل المستخدمين' },
  { key: 'users:archive', label: 'أرشفة المستخدمين' },
  { key: 'support:view', label: 'عرض الدعم والرسائل' },
  { key: 'support:assign', label: 'إسناد الرسائل' },
  { key: 'support:resolve', label: 'إغلاق الرسائل' },
  { key: 'content:view', label: 'عرض المحتوى' },
  { key: 'content:edit', label: 'تعديل المحتوى' },
  { key: 'notifications:send', label: 'إرسال الإشعارات' },
  { key: 'reports:view', label: 'عرض التقارير' },
  { key: 'settings:view', label: 'عرض الإعدادات' },
  { key: 'settings:edit', label: 'تعديل الإعدادات' },
  { key: 'settings:maintenance', label: 'إدارة الصيانة' },
  { key: 'access:view', label: 'عرض صلاحيات الوصول' },
  { key: 'access:manage', label: 'إدارة صلاحيات الوصول' },
  { key: 'roles:view', label: 'عرض الأدوار' },
  { key: 'roles:manage', label: 'إدارة الأدوار' },
  { key: 'admins:view', label: 'عرض حسابات الأدمن والمشرفين' },
  { key: 'admins:view_sensitive', label: 'عرض بيانات الأدمن بالكامل' },
  { key: 'admins:create', label: 'إنشاء أدمن أو مشرف' },
  { key: 'admins:cancel', label: 'إلغاء/تعطيل حساب الأدمن' },
  { key: 'admins:manage', label: 'إدارة حسابات الأدمن والمشرفين' },
  { key: 'audit:view', label: 'عرض سجل التدقيق' },
] as const;

export const DEFAULT_ROLE_TEMPLATES = [
  {
    id: 'super-admin',
    name: 'مدير النظام الرئيسي',
    description: 'أعلى صلاحية داخل النظام بالكامل.',
    locked: true,
    permissions: PERMISSION_CATALOG.map((permission) => permission.key),
  },
  {
    id: 'platform-operator',
    name: 'مشرف التشغيل',
    description: 'يدير الوظائف والشركات والطلبات والبلاغات اليومية.',
    locked: false,
    permissions: [
      'dashboard:view',
      'users:view',
      'users:edit',
      'users:archive',
      'companies:view',
      'companies:review',
      'companies:approve',
      'companies:password_reset',
      'companies:archive',
      'jobs:view',
      'jobs:create',
      'jobs:edit',
      'jobs:publish',
      'jobs:archive',
      'applications:view',
      'applications:update',
      'applications:assign',
      'applications:export',
      'support:view',
      'support:assign',
      'support:resolve',
      'reports:view',
      'notifications:send',
    ],
  },
  {
    id: 'content-manager',
    name: 'محرر المحتوى',
    description: 'يدير الصفحات الثابتة والنصوص والتنبيهات العامة.',
    locked: false,
    permissions: [
      'dashboard:view',
      'content:view',
      'content:edit',
      'settings:view',
      'notifications:send',
      'reports:view',
    ],
  },
  {
    id: 'support-manager',
    name: 'مسؤول الدعم',
    description: 'يتابع الرسائل الواردة والطلبات التي تحتاج تصعيد.',
    locked: false,
    permissions: [
      'dashboard:view',
      'applications:view',
      'applications:update',
      'support:view',
      'support:assign',
      'support:resolve',
      'reports:view',
      'notifications:send',
    ],
  },
  {
    id: 'auditor',
    name: 'مراجع داخلي',
    description: 'صلاحيات قراءة فقط مع التقارير وسجل التدقيق.',
    locked: false,
    permissions: [
      'dashboard:view',
      'users:view',
      'companies:view',
      'jobs:view',
      'applications:view',
      'support:view',
      'content:view',
      'settings:view',
      'reports:view',
      'roles:view',
      'audit:view',
    ],
  },
] as const;

export const STATIC_SITE_JOBS = [] as const;

export const STATIC_SITE_COMPANIES = [] as const;

export const DEFAULT_FAQ_ITEMS = [] as const;

export const DEFAULT_NOTIFICATION_TEMPLATES = [] as const;
